### PR TITLE
Update homepage.html

### PR DESCRIPTION
**Pull request by ykris45**

### CODE REVIEW

**Comment by nikooo777** [comment]
I feel like this change is too drastic. It's just a personal feeling so if someone else approves I'm fine with it, though I'd prefer to keep this label in a footer or anyway lower in the page and possibly smaller.

As I said on discord last week: the aim of this page is to let people open lbry urls on the app, not to make them download the app as I suppose one would already have it?

**Comment by NetOpWibby** [comment]
What is the point of this? I opened `open.lbry.io` and didn't see the original "Click to open" link. In addition, the selector for those kinds of links are hidden by default in the CSS. When would anyone see these buttons?

**Comment by nikooo777** [comment]
@NetOperatorWibby to hotlink things like:

https://scrn.storni.info/2018-08-24_11-34-14-740701802.png

**Comment by NetOpWibby** [comment]
Ah, now I understand.

@ykris45 This addition would be better placed outside of `#wrapper` to address @nikooo777's concerns.

**Comment by ykris45** [comment]
@NetOperatorWibby https://cdn.discordapp.com/attachments/363087279469756416/479697260687523840/unknown.png see this

**Comment by ykris45** [comment]
i think its outside in the wrapper section

**Comment by NetOpWibby** [comment]
Oh okay, that looks good to me.

**Comment by nikooo777** [comment]
Discussed on slack with Paul and agreed that this is sufficient. Will merge as is

**Pull request merged**
